use_frameworks!

platform :ios, '8.0'

source 'https://cdn.cocoapods.org/'

target 'FMDBMigrationManager_Example' do
  pod 'FMDBMigrationManager', :path => '../'

  target 'FMDBMigrationManager_Tests' do
    inherit! :search_paths

    
  end
end
